apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: bwe2p2nks-dotnet-basic
  janus-idp.io/tekton: bwe2p2nks-dotnet-basic
  backstage.io/kubernetes-id: bwe2p2nks-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bwe2p2nks-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
