apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: bwe2p2nks-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/bwe2p2nks-dotnet-basic-gitops